apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://10.5.0.51:9090
    basicAuth: false
    isDefault: true
    editable: true
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://10.5.0.53:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    uid: tempo
    jsonData:
      httpMethod: GET
      streamingEnabled:
        search: true
