networks:
  gigi:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24
          gateway: 10.5.0.1

volumes:
  prometheus_data: { }
  grafana_data: { }

services:
  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - "3000:3000"
    networks:
      - gigi

  tigerbeetle_0:
    image: ghcr.io/tigerbeetle/tigerbeetle
    container_name: apigw-tomcat
    command: "start --addresses=0.0.0.0:4342 /data/0_0.tigerbeetle"
    volumes:
      - ./data:/data
    security_opt:
      - "seccomp=unconfined"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    expose:
      - 4342
    ports:
      - 4342:4342
    networks:
      gigi:
        ipv4_address: 10.5.0.50

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    expose:
      - 9090
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      gigi:
        ipv4_address: 10.5.0.51

  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      gigi:
        ipv4_address: 10.5.0.52
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - tigerbeetle_0

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/var/tempo
    ports:
      - "3200:3200" # tempo
      - "9095:9095" # tempo grpc
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      - "9411:9411"   # zipkin
    networks:
      gigi:
        ipv4_address: 10.5.0.53
