{
 "title": "Rate limiting",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Rate limiting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(ratelimit_limited_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response codes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count[$__range])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "By user",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(user) (rate(ratelimit_seconds_count[$__rate_interval]))",
     "legendFormat": "user: {{user}}"
    }
   ]
  }
 ]
}