global:
  scrape_interval:     15s
  evaluation_interval: 15s

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'ratelimiting_tigerbeetle'
    scrape_interval: 10s
    honor_labels: true
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ '10.5.0.52:8081' ]
